### ISSUE TITLE
Falta a função transformacao_tracos

### ISSUE THREAD

**Issue by rcrocha** [michelpf/fiap-ml-visao-computacional#1]
Em:
fiap-ml-visao-computacional/aula-4-classificacao-objetos-analise-facial/classificacao-objetos.ipynb

A função: "transformacao_tracos" não esta definida.

**Comment by michelpf** [comment]
Era um erro mesmo. Precisa tirar essa função e colocar diretamente a imagem.
Eu acabei de revisar tudo, dá uma olhada agora, por favor.
